name: Conftest
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
       contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" openpolicyagent/conftest test --policy policy/ .github/workflows